<?php

/**
 * @file
 * Contains dms_instance.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Access\AccessResult;

/**
 * Implements hook_help().
 */
function dms_instance_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dms_instance module.
    case 'help.page.dms_instance':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('CanadaHelps DMS instance module') . '</p>';
      return $output;

    default:
  }
}

function dms_instance_jsonapi_entity_filter_access(\Drupal\Core\Entity\EntityTypeInterface $entity_type, \Drupal\Core\Session\AccountInterface $account) {

  // For every entity type that has an admin permission, allow access to filter
  // by all entities of that type to users with that permission.
  if ($admin_permission = TRUE) {
    return [
      JSONAPI_FILTER_AMONG_ALL => AccessResult::allowedIfHasPermission($account, $admin_permission),
    ];
  }
}
